source "https://rubygems.org"

ruby "3.2.0"

gem "rails", "~> 7.0.5"

gem "sprockets-rails"

gem 'unicorn', '~> 6.1.0'

gem 'pg'

gem 'sidekiq'

gem 'redis-rails'

gem "importmap-rails"

gem "turbo-rails"

gem "stimulus-rails"

gem "jbuilder"

gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
